ALTER TABLE table_order_items
    DROP CONSTRAINTS table_order_items_fk1;

DROP TABLE table_order_items CASCADE CONSTRAINTS;
DROP TABLE table_orders CASCADE CONSTRAINTS;
DROP TABLE table_customers CASCADE CONSTRAINTS;
DROP TABLE table_cameras CASCADE CONSTRAINTS;
DROP TABLE table_lenses CASCADE CONSTRAINTS;
DROP TABLE table_equipment CASCADE CONSTRAINTS;
DROP TABLE table_films CASCADE CONSTRAINTS;

CREATE TABLE table_cameras
(
    camera_id  int(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    image_url  varchar(200),
    category   varchar(50),
    name       varchar(100)                                  NOT NULL,
    price      decimal(10, 2)                                  NOT NULL,
    stock      int(10) DEFAULT 0 NOT NULL,
    created_at date       DEFAULT SYSDATE                     NOT NULL,
    updated_at date
);

CREATE TABLE table_lenses
(
    lens_id    int(10, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    image_url  varchar(200),
    category   varchar(50),
    aperture   varchar(50)                                   NOT NULL,
    name       varchar(100)                                  NOT NULL,
    price      int(10, 2)                                  NOT NULL,
    stock      int(10, 0) DEFAULT 0                        NOT NULL,
    created_at date       DEFAULT SYSDATE                  NOT NULL,
    updated_at date
);

CREATE TABLE table_equipment
(
    table_equipment_id int(10, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    image_url    varchar(200),
    category     varchar(50),
    name         varchar(100)                                  NOT NULL,
    price        int(10, 2)                                  NOT NULL,
    stock        int(10, 0) DEFAULT 0                        NOT NULL,
    created_at   date       DEFAULT SYSDATE                  NOT NULL,
    updated_at   date
);

CREATE TABLE table_films
(
    film_id    int(10, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    image_url  varchar(200),
    category   varchar(50),
    name       varchar(100)                                  NOT NULL,
    price      int(10, 2)                                  NOT NULL,
    stock      int(10, 0) DEFAULT 0                        NOT NULL,
    created_at date       DEFAULT SYSDATE                  NOT NULL,
    updated_at date
);

CREATE TABLE table_customers
(
    customer_id int(10, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    first_name  varchar(50),
    last_name   varchar(50),
    email       varchar(100)                                  NOT NULL UNIQUE,
    password    varchar(100)                                  NOT NULL,
    address     varchar(200),
    city        varchar(50),
    zip         varchar(10),
    created_at  date DEFAULT SYSDATE                           NOT NULL,
    updated_at  date
);

CREATE TABLE table_orders
(
    order_id         int(10, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    customer_id      int(10)                                     NOT NULL,
    order_date       date                                           NOT NULL,
    status           varchar(20)                                   NOT NULL,
    total_amount     int(10, 2)                                  NOT NULL,
    shipping_address varchar(200),
    payment_method   varchar(30),
    created_at       date DEFAULT SYSDATE                           NOT NULL,
    updated_at       date
);

CREATE TABLE table_order_items
(
    order_item_id int(10, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    order_id      int(10)                                     NOT NULL,
    product_type  varchar(20)                                   NOT NULL,
    product_id    int(10)                                     NOT NULL,
    quantity      int(10)                                     NOT NULL,
    unit_price    int(10, 2)                                  NOT NULL,
    total_price   int(10, 2)                                  NOT NULL,
    created_at    date DEFAULT SYSDATE                           NOT NULL,
    updated_at    date
);

-- CONSTRAINTS
ALTER TABLE table_cameras
    ADD CONSTRAint ck_priceC CHECK (price > 0);
ALTER TABLE table_cameras
    ADD CONSTRAint ck_stockC CHECK (stock >= 0);

ALTER TABLE table_lenses
    ADD CONSTRAint ck_priceL CHECK (price > 0);
ALTER TABLE table_lenses
    ADD CONSTRAint ck_stockL CHECK (stock >= 0);

ALTER TABLE table_equipment
    ADD CONSTRAint ck_priceE CHECK (price > 0);
ALTER TABLE table_equipment
    ADD CONSTRAint ck_stockE CHECK (stock >= 0);

ALTER TABLE table_films
    ADD CONSTRAint ck_priceF CHECK (price > 0);
ALTER TABLE table_films
    ADD CONSTRAint ck_stockF CHECK (stock >= 0);

ALTER TABLE table_orders
    ADD CONSTRAint table_orders_fk1 FOREIGN KEY (customer_id) REFERENCES table_customers (customer_id);
ALTER TABLE table_orders
    ADD CONSTRAint ck_table_orders_status
        CHECK (status IN ('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled'));
ALTER TABLE table_orders
    ADD CONSTRAint ck_total_amount
        CHECK (total_amount >= 0);

ALTER TABLE table_order_items
    ADD CONSTRAint table_order_items_fk1 FOREIGN KEY (order_id) REFERENCES table_orders (order_id) ON DELETE CASCADE;
ALTER TABLE table_order_items
    ADD CONSTRAint ck_table_order_items_quantity
        CHECK (quantity > 0);
ALTER TABLE table_order_items
    ADD CONSTRAint ck_table_order_items_unit_price
        CHECK (unit_price >= 0);
ALTER TABLE table_order_items
    ADD CONSTRAint ck_table_order_items_total_price
        CHECK (total_price >= 0);
ALTER TABLE table_order_items
    ADD CONSTRAint ck_table_order_items_product_type
        CHECK (product_type IN ('Camera', 'Lens', 'Film', 'table_equipment'));

-- triggers
CREATE OR REPLACE TRIGGER table_cameras_before_update
    BEFORE UPDATE
    ON table_cameras
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;

CREATE OR REPLACE TRIGGER table_lenses_before_update
    BEFORE UPDATE
    ON table_lenses
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER table_films_before_update
    BEFORE UPDATE
    ON table_films
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER table_equipment_before_update
    BEFORE UPDATE
    ON table_equipment
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER table_customers_before_update
    BEFORE UPDATE
    ON table_customers
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER table_orders_before_update
    BEFORE UPDATE
    ON table_orders
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER table_order_items_before_update
    BEFORE UPDATE
    ON table_order_items
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;
/